// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2yRMRJrz72rzLCffTSIFMKL8bgu8Nb9o',
    appId: '1:226777627112:web:81125ef067cb5f9a890c5d',
    messagingSenderId: '226777627112',
    projectId: 'xbus-f2b3b',
    authDomain: 'xbus-f2b3b.firebaseapp.com',
    storageBucket: 'xbus-f2b3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHLOHLAa2VpXz5L_tCgTydzpkVDczBeY',
    appId: '1:226777627112:android:bb63bd75f8759930890c5d',
    messagingSenderId: '226777627112',
    projectId: 'xbus-f2b3b',
    storageBucket: 'xbus-f2b3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi_1fr6GbFq22oQ5jNPeZQdmCnPsHMvvM',
    appId: '1:226777627112:ios:33bae33566c9cc0b890c5d',
    messagingSenderId: '226777627112',
    projectId: 'xbus-f2b3b',
    storageBucket: 'xbus-f2b3b.appspot.com',
    iosClientId: '226777627112-gqoijllme0r98a4ru7odkkssd0ffjms8.apps.googleusercontent.com',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi_1fr6GbFq22oQ5jNPeZQdmCnPsHMvvM',
    appId: '1:226777627112:ios:33bae33566c9cc0b890c5d',
    messagingSenderId: '226777627112',
    projectId: 'xbus-f2b3b',
    storageBucket: 'xbus-f2b3b.appspot.com',
    iosClientId: '226777627112-gqoijllme0r98a4ru7odkkssd0ffjms8.apps.googleusercontent.com',
    iosBundleId: 'com.example.driver',
  );
}
