from .ajaxExample import *
from .ticketsViews import *
from .homeViews import *
from .regionsViews import *
from .routesViews import *
from .stopsViews import *
from .vehiclesViews import *
from .driversViews import *
from .tripsViews import *
from .reportRoutesViews import *
from .reportTicketsViews import *
from .reportRegionsViews import *
